// getAll
export const FETCH_REQUEST = "FETCH_SALE_REQUEST";
export const FETCH_SUCCESS = "FETCH_SALE_SUCCESS";
export const FETCH_FAILURE = "FETCH_SALE_FAILURE";

// postData
export const POST_REQUEST = "POST_SALE_REQUEST";
export const POST_SUCCESS = "POST_SALE_SUCCESS";
export const POST_FAILURE = "POST_SALE_FAILURE";

// deleteData
export const DELETE_REQUEST = "DELETE_SALE_REQUEST";
export const DELETE_SUCCESS = "DELETE_SALE_SUCCESS";
export const DELETE_FAILURE = "DELETE_SALE_FAILURE";

// updateData
export const UPDATE_REQUEST = "UPDATE_SALE_REQUEST";
export const UPDATE_SUCCESS = "UPDATE_SALE_SUCCESS";
export const UPDATE_FAILURE = "UPDATE_SALE_FAILURE";
